config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :characters, only: [:index, :show] do
    collection do
      get 'home'
    end
    member do
      get 'show'
    end
  end

  resources :comics, only: [:index]

end

app/models/character_catalog.rb
class CharacterCatalog < MarvelWorld

  #characters(nil, "162, 30090")
  def characters(limit=nil, comic_ids=nil)
    op = self.options
    op[:query][:limit] = limit if limit
    op[:query][:comics] = comic_ids if comic_ids
    self.class.get("/characters", op)
  end

  def total_characters_number
    #only one character is enough to know total characters because api is returning total number of characters
    res = self.characters(1)
    res.parsed_response['data']['total']
  end

  def character_thumbnail_url(character_id)
    res = self.class.get("/characters/#{character_id}", self.options)
    thumbnail = res.parsed_response['data']['results'].first['thumbnail'] rescue {}
    "#{thumbnail['path']}.#{thumbnail['extension']}"
  end

  def character_names(limit=nil, comic_ids=nil)
    res = self.characters(limit, comic_ids)
    res.parsed_response['data']['results'].collect{|c| c['name']}
  end

  def character(character_id)
    self.class.get("/characters/#{character_id}", self.options)
  end
end

app/models/comic_catalog.rb
class ComicCatalog < MarvelWorld

  def comic(comic_id)
    res = self.class.get("/comics/#{comic_id}", self.options)
  end

end

app/models/marvel_world.rb
class MarvelWorld
  include HTTParty

  base_uri 'http://gateway.marvel.com/v1/public'

  def ts
    ts = Time.now.to_i
  end

  def auth_hash(timestamp)
    Digest::MD5.hexdigest("#{timestamp}#{Rails.application.secrets.private_key}#{Rails.application.secrets.public_key}")
  end

  def options
    time_stamp = ts
    { query: {ts: time_stamp, apikey: Rails.application.secrets.public_key, hash: auth_hash(time_stamp)} }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    character_catalog = CharacterCatalog.new
    res = character_catalog.characters
    @characters = res.parsed_response['data']['results']
  end

  def show
    character_catalog = CharacterCatalog.new
    res = character_catalog.character(params[:id])
    @character = res.parsed_response['data']['results'].first
  end

  def home

  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
  def index

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_character.html.erb
<div class='panel panel-default'>
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to character['name'], character_path(character['id']) %></h3>
  </div>
  <div class="panel-body">
    <p><%= character['id'] %></p>
    <p><%= image_tag("#{character['thumbnail']['path']}.#{character['thumbnail']['extension']}") %></p>
  </div>
</div>

app/views/characters/home.html.erb
<h1>Marvel Characters Live Here</h1>

<br>
<p>To view all character please click on the link below </p>
<p><%= link_to 'All Characters', characters_path %></p>

app/views/characters/index.html.erb
<h1>Marvel Characters Live Here</h1>
<br>
<p>Total Characters : <%= @characters.count %></p>
<%= render partial: "character", collection: @characters %>

app/views/characters/show.html.erb
<%= render partial: "character", locals: {character: @character} %>

app/views/comics/index.html.erb
<h1>This is under construction</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Marvel" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Marvel</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Characters", home_characters_path %></li>
            <li><%= link_to "Comics", comics_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Characters", home_characters_path  %></li>
              <li><%= link_to "Comics", comics_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome To Marvel World</h1>